# Generated by Django 5.0.6 on 2026-06-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='empleados.empleado'),
        ),
    ]
