# Generated by Django 5.0.6 on 2026-06-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ventas', 'Ventas'), ('compra', 'Compra'), ('inventario', 'Inventario'), ('auditoria', 'Auditoria'), ('prediccion', 'Prediccion')], max_length=12)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel')], max_length=5)),
                ('ruta_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(default='generado', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Reporte generado',
                'verbose_name_plural': 'Reportes generados',
                'db_table': 'reporte_generado',
            },
        ),
    ]
