# Generated by Django 5.0.6 on 2026-06-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraSugerida',
            fields=[
                ('id_sugerencia', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_sugerida', models.IntegerField()),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('bajo_stock', 'Bajo stock'), ('prediccion_demanda', 'Prediccion de demanda')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='compras_sugeridas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Compra sugerida',
                'verbose_name_plural': 'Compras sugeridas',
                'db_table': 'compra_sugerida',
            },
        ),
        migrations.CreateModel(
            name='DatosPrediccion',
            fields=[
                ('id_prediccion', models.AutoField(primary_key=True, serialize=False)),
                ('demanda_predicha', models.IntegerField()),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_prediccion', models.DateField()),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Dato de prediccion',
                'verbose_name_plural': 'Datos de prediccion',
                'db_table': 'datos_prediccion',
            },
        ),
        migrations.CreateModel(
            name='DemandasHistoricas',
            fields=[
                ('id_demanda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad_vendida', models.IntegerField()),
                ('precio_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='demandas_historicas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Demanda historica',
                'verbose_name_plural': 'Demandas historicas',
                'db_table': 'demandas_historicas',
            },
        ),
        migrations.CreateModel(
            name='MetricasVentas',
            fields=[
                ('id_metrica', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=50)),
                ('cantidad_vendida', models.IntegerField()),
                ('ingresos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rentabilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Metrica de ventas',
                'verbose_name_plural': 'Metricas de ventas',
                'db_table': 'metricas_ventas',
            },
        ),
    ]
