# Generated by Django 5.0.6 on 2026-06-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAuditoria',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('tipo_operacion', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=6)),
                ('fecha_operacion', models.DateField(auto_now_add=True)),
                ('hora_operacion', models.TimeField(auto_now_add=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bitacora de auditoria',
                'verbose_name_plural': 'Bitacoras de auditoria',
                'db_table': 'bitacora_auditoria',
            },
        ),
    ]
