# Generated by Django 5.0.6 on 2026-06-04 00:45

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('abandonado', 'Abandonado'), ('convertido_venta', 'Convertido a venta')], default='abandonado', max_length=20)),
                ('total_temporal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'carrito',
            },
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id_detalle_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('cantidad'), '*', models.F('precio_unitario')), output_field=models.DecimalField(decimal_places=2, max_digits=12))),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detalle de carrito',
                'verbose_name_plural': 'Detalles de carrito',
                'db_table': 'detalle_carrito',
            },
        ),
    ]
