# Generated by Django 5.0.6 on 2026-06-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='carritos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='carrito',
            field=models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='carrito.carrito'),
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_carrito', to='productos.producto'),
        ),
    ]
